---
title: "Steps to convert moored ADCP ODF files to a single NetCDF file"
author: "Jaimie Harbin"
date: "`r Sys.Date()`"
output: pdf_document
---

# Introduction

This vignette discusses the steps to convert a moored acoustic doppler current profiler (ADCP) ODF file to a NetCDF file. To convert a list of ADCP ODF files run the ADCP.R code. Make sure to change line 18 to direct the code to your own ODF files. The data used in this study is from the Davis Strait.

# Step one: Create the appropriate data frame

This data frame contains the standard_name, unit, and GF3 code for the following parameters:
sensor_depth_below_sea_surface, eastward_sea_water_velocity, height_above_mean_sea_level,         northward_sea_water_velocity, sea_water_pressure, platform_pitch_angle,                            platform_roll_angle",speed_of_sound_in_sea_water,time,upward_sea_water_velocity,unknown_WMO_code,  indicative_error_from_multibeam_acoustic_doppler_velocity_profiler_in_sea_water,
signal_intensity_from_multibeam_acoustic_doppler_velocity_sensor_in_sea_water,temperature_1990_scale,"percent_good_ping".

# Step two: Compile one adp object from multiple ODF files using odf2adp()

The `odf2adp()` function is Emily's function, which eads in a set of odf files and compiles into adp object, is capable of recognizing missing bins or missing odf files and inserting NA's in
appropriate slot of data variables

# Step three: Create a single NetCDF using oceNc_create() and standard_name()

The `oceNc_create()` function is Emily's function, which exports an adp object to a NetCDF using variables and metadata within adp combined with optional additional metadata. There are a number of steps that go into this including:

1. Setting dimensions
2. Defining variables
3. Writting definitions to the NetCDF file using nc_create()
4. Insert variables into the NetCDF file using ncvar_put()
5. Writing data into existing NetCDF using ncatt_put()

When the names and units of variables are being inserted, the function `standard_name()` is used, which determines the standard_name and units from the desired GF3 code.


